### ISSUE TITLE
bar/** seems to work differently than .gitignore

### ISSUE THREAD

**Issue by littlebtc** [denormal/go-gitignore#1]
For files like
<pre><code>
.
├ foo
│  └ bar
│     └ some_file.txt
└ bar
   └ other_file.txt
</pre></code>

When I ignore:

    bar/**

Both `foo/bar/some_file.txt` and `bar/other_file.txt` will be ignored.

But for `.gitignore`, only `bar/other_file.txt` will be ignored.

**Comment by denormal** [comment]
You are correct - thanks for the bug report. I'll get a fix out as soon as I can.

**Comment by denormal** [comment]
This should now be fixed. Please let me know if the fix does not work as you expected.

Apologies for the delay in correcting this.
