### ISSUE TITLE
Parser panics on line containing just whitespace

### ISSUE THREAD

**Issue by bradleyjkemp** [denormal/go-gitignore#2]
Hi, just ran into a bug where lines that only contain whitespace cause a panic in the parser. This is quite a tricky one to diagnose because such lines are very hard to spot.

Reproduction:
```go
package main

import "github.com/denormal/go-gitignore"

func main() {
	// or match against a repository
	//  - here we match a directory path relative to the repository
	matcher, err := gitignore.NewRepository( "/tmp/panic" )
	if err != nil {
		panic(err)
	}

	matcher.Relative("panic_test", false)
}
```
Panics if the file `/tmp/panic/.gitignore` contains a line with a single space e.g.
```
# Next line contains just whitespace
 
```

**Comment by denormal** [comment]
Yep - bad bounds checking in NewPattern(). I've applied a fix - please let me know if this resolves the issue for you.

**Comment by bradleyjkemp** [comment]
Fabulous, thank you. Can confirm this has solved the issue.
